#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May 18 12:15:34 2020

@author: Pedro_Martínez
"""
#import pandas as pd
import json


version = int(input( 'teclea: 1 (sentimiento ponderado),\n2 (sentimiento sin ponderar),\n3 (no asignar)\n'))

def dictionary(texto):
    sentimientos = open(texto)         
    valores = {} 
    for line in sentimientos: 
        term, val = line.split("\t") 
        valores[term] = int(val) 
    return valores

val_dict = dictionary("Sentimientos.txt")

def feelings(file):

    t = open(file,"r")
    Lines = t.readlines()
    t.close()
    
    tweets = {}
    info_tweet = {}
    for pos,line in enumerate(Lines):
        tweets[pos] = json.loads(line)
# only the files that contain: "created_at" have text
        if 'created' in str(tweets[pos].keys()):
            text = tweets[pos]['text']
            sentimiento = 0
            count = 0
            
            for  word in text.split():
                for key, value in val_dict.items():
                    if word.lower()==key:
                        sentimiento+=value
                        count+=1
                        continue
   
                    
            if sentimiento!=0:
                count_words = len(text.split())-count
                if version ==1:
                    sent_medio = len(text.split())/sentimiento
                    info_tweet[text] = sentimiento+sent_medio*count_words
                    
                elif version == 2:
                    sent_medio = sentimiento
                    info_tweet[text] = sentimiento+sent_medio*count_words
                    
                elif  version==3:
                    info_tweet[text] = sentimiento
                else:
                    print('choose 1 2 or 3')
#                info_tweet[text] = sentimiento
            
    return info_tweet

usefulTweets = feelings("Tweets.txt")

number_of_tweets = 5
while number_of_tweets>0:
    print('the tweet:\n',list(usefulTweets)[number_of_tweets],'...\nhas sentiment of:')
    print (list(usefulTweets.values())[number_of_tweets],'\n')
    number_of_tweets-=1